// src/candidate/candidate.service.ts
import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma.service';
import { CandidateDto } from './dto/create-candidate.dto';
import { join } from 'path';
import { extname } from 'path';
import { UpdateCandidateDto } from './dto/update-candidate.dto';

@Injectable()
export class CandidateService {
  constructor(private prisma: PrismaService) {}

  async uploadFileMulter(
    file: Express.Multer.File,
    candidateData: CandidateDto,
  ): Promise<any> {
    console.log('File ', file);

    const allowedExtensions = ['.pdf', '.doc', '.docx'];
    const fileExtension = extname(file.originalname);

    if (!allowedExtensions.includes(fileExtension)) {
      throw new Error(
        'Invalid file type. Only PDF and Word documents are allowed.',
      );
    }

    // Use the filename generated by Multer's diskStorage configuration
    const uniqueFileName = file.filename;

    const yearsOfExperience = Number(candidateData.yearsOfExperience);
    const noticePeriod = Number(candidateData.noticePeriod);

    let skillsArray: string[] = [];

    if (candidateData.skills) {
      if (typeof candidateData.skills === 'string') {
        skillsArray = candidateData.skills.split(',').map((s) => s.trim());
      } else if (Array.isArray(candidateData.skills)) {
        skillsArray = candidateData.skills.map((s) => s.trim());
      }
    }


    // Create a new candidate record in the database
    const createdCandidate = await this.prisma.candidate.create({
      data: {
        firstName: candidateData.firstName,
        lastName: candidateData.lastName,
        mobile: candidateData.mobile,
        email: candidateData.email,
        yearsOfExperience,
        education: candidateData.education,
        noticePeriod,
        resume: file.filename,
        skills: {
          connectOrCreate: skillsArray.map((name) => ({
            where: { name },
            create: { name },
          })),
        },
      },
      include: {
        skills: true,
      },
    });

    console.log('Created Candidate: ', createdCandidate);

    const filePath = join(process.cwd(), 'uploads', uniqueFileName);

    console.log('FilePath ', filePath);

    return createdCandidate;
  }

  // get all candidate
  async findAll() {
    return await this.prisma.candidate.findMany({ include: { skills: true } });
  }

  // Get candidate by ID
  async findOne(id: number) {
    return await this.prisma.candidate.findUnique({
      where: { id },
      include: { skills: true },
    });
  }

  // delete by id
  async remove(id: number){
    return await this.prisma.candidate.delete({where: {id}})
  }

  // update by id
   async update(id: number, candidateData: UpdateCandidateDto) {
    let skillsArray: string[] = [];
    if (candidateData.skills) {
      if (typeof candidateData.skills === 'string') {
        skillsArray = candidateData.skills.split(',').map((s) => s.trim());
      } else if (Array.isArray(candidateData.skills)) {
        skillsArray = candidateData.skills.map((s) => s.trim());
      }
    }

    return await this.prisma.candidate.update({
      where: { id },
      data: {
        firstName: candidateData.firstName,
        lastName: candidateData.lastName,
        mobile: candidateData.mobile,
        email: candidateData.email,
        yearsOfExperience: Number(candidateData.yearsOfExperience),
        education: candidateData.education,
        noticePeriod: Number(candidateData.noticePeriod),
        skills: skillsArray.length
          ? {
              connectOrCreate: skillsArray.map((name) => ({
                where: { name },
                create: { name },
              })),
            }
          : undefined,
      },
      include: { skills: true },
    });
  }


}
